# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bundle' do
  pod 'Stripe', '~> 14.0.0'
  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
